name: Gradle Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew test

      - uses: akhileshns/heroku-deploy@v3.12.12
        name: Deploy to Heroku
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "space-mines"
          heroku_email: "twcrone@gmail.com"
